---
        - name: Playbook
          hosts: all
          become: yes
          tasks:
                - name: Update all packages to their latest version
                  ansible.builtin.apt:
                          name: "*"
                          state: latest
                          autoclean: yes
                          autoremove: yes
